//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendance
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> sDate { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Type { get; set; }
        public Nullable<byte> Present { get; set; }
        public Nullable<byte> Absent { get; set; }
        public Nullable<byte> Leave { get; set; }
        public Nullable<byte> Offday { get; set; }
    }
}
